language: node_js
node_js:
  - "5.4"
  - "4.2"
  - "0.12"
matrix:
  allow_failures:
    - node_js: "4.2"
    - node_js: "5.4"
script: 
  - "npm run lint"
  - "npm test"
  - "npm run test-cov"
after_script: "npm install coveralls && cat ./test/coverage/lcov.info | coveralls"