sudo: false
language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libgnome-keyring-dev
matrix:
  allow_failures:
    - node_js: "4"
    - node_js: "5"
script:
  - "npm test"
  - "npm run test-ci"
after_script: "npm install coveralls && npm run coverage"